In [0]:
import torch

In [3]:
x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [0]:
x = torch.zeros([2,5])

In [5]:
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [6]:
x.shape

torch.Size([2, 5])

In [0]:
y = torch.rand([2,5])

In [8]:
y.shape

torch.Size([2, 5])

In [9]:
print(y)

tensor([[0.9250, 0.2053, 0.9749, 0.2721, 0.1574],
        [0.2898, 0.2439, 0.4996, 0.1043, 0.6419]])


In [11]:
y.view([1,10])

tensor([[0.9250, 0.2053, 0.9749, 0.2721, 0.1574, 0.2898, 0.2439, 0.4996, 0.1043,
         0.6419]])

In [13]:
 y

tensor([[0.9250, 0.2053, 0.9749, 0.2721, 0.1574],
        [0.2898, 0.2439, 0.4996, 0.1043, 0.6419]])

In [0]:
y = y.view([1,10])

In [15]:
y

tensor([[0.9250, 0.2053, 0.9749, 0.2721, 0.1574, 0.2898, 0.2439, 0.4996, 0.1043,
         0.6419]])